spring.application.name=studentslistapi
spring.application.version=1.1
spring.application.description=API documentation for student List api.
server.port=8081
jwt.secret = secret
eureka.client.serviceUrl.defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
eureka.instance.preferIpAddress: true

#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

#DEPENDENCIES FOR SPANID AND TRACE ID -DISTRIBUTED TRACING
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/
# Ensure logs include Trace and Span IDs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId:-},%X{spanId:-}] - %msg%n

#Java
#If you have Java 17 or higher installed, the quickest way to get started is to fetch the latest release as a self-contained executable jar:
#curl -sSL https://zipkin.io/quickstart.sh | bash -s
#java -jar zipkin.jar

####################################	START OF HIKARI DATASOURCE 	########################
datasource.student.driver-class-name=com.mysql.cj.jdbc.Driver
datasource.student.jdbc-url=jdbc:mysql://localhost:3306/student
datasource.student.username=studentdbuser
datasource.student.password=Nagu@9046N
datasource.student.pool-name=Pool-4-prod
datasource.student.initialize=true

####################################	 START OF HIBERNATE DATASOURCE	########################

hdatasource.student.driver-class-name=com.mysql.cj.jdbc.Driver
hdatasource.student.jdbc-url=jdbc:mysql://localhost:3306/student
hdatasource.student.username=studentdbuser
hdatasource.student.password=Nagu@9046N
hdatasource.student.pool-name=Pool-hdatasource-student-prod
hdatasource.student.initialize=true

hdatasource.marks.driver-class-name=com.mysql.cj.jdbc.Driver
hdatasource.marks.jdbc-url=jdbc:mysql://localhost:3306/marks
hdatasource.marks.username=studentdbuser
hdatasource.marks.password=Nagu@9046N
hdatasource.marks.pool-name=Pool-hdatasource-marks-prod
hdatasource.marks.initialize=true

hdatasource.jdbc.show-sql=true
hdatasource.sql-dialect=org.hibernate.dialect.MySQL5Dialect

##Turn Statistics on and log SQL stmts
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
##If want to see very extensive logging
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.type=trace
logging.level.org.hibernate.stat=debug

#Hibernate create the schema using entity classes 
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none //Schema will be created using schema.sql and data.sql files


####################################	END START OF HIBERNATE DATASOURCE	########################


spring.jackson.serialization.order-map-entries-by-keys=true


ERROR.CODE.200=OK
ERROR.CODE.201=Created
ERROR.CODE.400=Bad Request
ERROR.CODE.401=Unauthorized
ERROR.CODE.403=Forbidden
ERROR.CODE.404=Student ID Not Found
ERROR.CODE.409=Conflict
ERROR.CODE.500=Internal Server Error



mail.host=smtp.example.com
mail.port=587
mail.username=user
mail.password=password